name: Browser Test
on:
  pull_request:
  push:
  schedule: [cron: "0 8 * * 5"] # 8:00 on Fridays

jobs:
  test:
    name: Browser Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        profile: minimal
        target: wasm32-unknown-unknown
    - run: cargo +stable install wasm-bindgen-cli --vers "^0.2.71"
    - run: cat CI.toml >> Cargo.toml
    - run: cargo +stable test --workspace --target wasm32-unknown-unknown --no-default-features
    - run: cargo +stable test --workspace --target wasm32-unknown-unknown
    - run: cargo +stable test --workspace --target wasm32-unknown-unknown --all-features
