name: Browser Test
on:
  pull_request:
  push:
  schedule: [cron: "0 8 * * 5"] # 8:00 on Fridays

jobs:
  test:
    name: Browser Test
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - run: cargo install wasm-bindgen-cli --vers "^0.2.71"
    - run: cat CI.toml >> Cargo.toml
    - run: cargo test --workspace --target wasm32-unknown-unknown
    - run: cargo test --workspace --target wasm32-unknown-unknown --all-features
